# Generated by Django 5.2.7 on 2025-10-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('donated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WeddingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride_name', models.CharField(max_length=100)),
                ('groom_name', models.CharField(max_length=100)),
                ('wedding_date', models.DateField()),
                ('venue_name', models.CharField(max_length=200)),
                ('venue_address', models.TextField()),
                ('ceremony_time', models.TimeField()),
                ('reception_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('hero_image_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Wedding Information',
            },
        ),
    ]
